---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://m8b.gamerselimiko.workers.dev/
polling_headers: ''
name: Magic 8-Ball
refresh_interval: 60
